import { expect, test } from "@playwright/test"

test("Sparky formats streamed and saved Markdown in the paper popup and full chat", async ({ page }, info) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto("/paper/e2e-grounding-paper")
  await expect(page.getByRole("heading", { name: "E2E Grounding Paper", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Open Sparky chat", exact: true }).click()
  const panel = page.getByRole("dialog", { name: "Chat with Sparky" })
  await panel.getByLabel("Message Sparky").fill("STREAMING-FIXTURE MARKDOWN-FIXTURE: Explain CNNT.")
  await panel.getByRole("button", { name: "Send", exact: true }).click()
  const draft = panel.locator("[data-streaming-text]")
  await expect(draft.locator("strong")).toHaveText("CNNT")
  expect(await draft.locator("p").last().evaluate(el => getComputedStyle(el, "::after").animationName)).not.toBe("none")
  await page.screenshot({ path: info.outputPath("markdown-streaming.png") })
  await expect(draft).toBeHidden({ timeout: 15_000 })
  await expect(panel.locator("li strong").first()).toHaveText("General background on CNNT's design.")
  await expect(panel.locator('ol[start="2"] li strong')).toHaveText("This paper's results.")
  await expect(panel.locator("em")).toHaveText("background")
  await expect(panel.getByRole("button", { name: "E2E Grounding Paper", exact: true })).toBeVisible()
  await expect(panel.getByRole("button", { name: "Save to knowledge base", exact: true })).toBeVisible()
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(panel).toBeInViewport({ ratio: 1 })
    expect(await panel.locator("table").evaluate(el => el.parentElement!.scrollWidth > el.parentElement!.clientWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`markdown-popup-${width}.png`) })
  }
  await panel.getByRole("link", { name: "Open full conversation" }).click()
  await expect(page).toHaveURL(/\/chat\/chat_/)
  await page.reload()
  await expect(page.locator("main li strong").first()).toHaveText("General background on CNNT's design.")
  await expect(page.locator("main")).not.toContainText("**General background")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath("markdown-saved-mobile.png") })
})
