import { expect, test, chromium, type Browser } from "@playwright/test"
import { importTool, resetTools, startTool, snapshot, providerRows, readRunFile } from "./fixtures/modular"

test("real instruction workflow survives navigation and browser close without duplicate synthesis", async ({ request, baseURL }, info) => {
  const firstBrowser = await chromium.launch()
  let secondBrowser: Browser | undefined
  try {
    const firstContext = await firstBrowser.newContext({ baseURL, storageState: await request.storageState() })
    const page = await firstContext.newPage()
    await resetTools()
    const { ref } = await importTool(request, "Background acceptance")
    const run = await startTool(request, ref, "MODULAR:background")
    await expect.poll(async () => (await providerRows("background")).some(r => r.phase === "review-synthesis")).toBe(true)
    await page.goto(`/tools/runs/${run.id}`)
    await expect(page.getByText("Working", { exact: true })).toBeVisible()
    await expect(page.getByRole("heading", { name: "Synthetic evidence report", exact: true })).toBeVisible()
    await expect(page.getByText("Working", { exact: true })).toBeVisible()
    await page.goto("/wiki")
    await page.goto(`/tools/runs/${run.id}`)
    await expect(page.getByText("Working", { exact: true })).toBeVisible()
    await expect(page.getByRole("heading", { name: "Synthetic evidence report", exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath("active-after-navigation.png"), fullPage: true })
    const state = await page.context().storageState()
    await firstBrowser.close()
    expect(firstBrowser.isConnected()).toBe(false)
    secondBrowser = await chromium.launch()
    const second = await secondBrowser.newContext({ baseURL, storageState: state })
    const reopened = await second.newPage()
    await reopened.goto(`/tools/runs/${run.id}`)
    await expect(reopened.getByText("Completed", { exact: true })).toBeVisible({ timeout: 25000 })
    expect((await providerRows("background")).filter(r => r.phase === "review-synthesis")).toHaveLength(1)
    const final = await snapshot(request, run.id)
    const usage = await readRunFile(run.id, "usage.json")
    expect(final.usage.modelCalls).toBe(3)
    expect(new Set(usage.attempts.map((a: { ticket: { id: string } }) => a.ticket.id)).size).toBe(3)
    const invocations = await providerRows("background")
    expect(new Set(invocations.map(row => row.id)).size).toBe(3)
    expect(invocations.map(row => row.workflowInputHash)).toEqual(usage.attempts.map((a: { ticket: { step: { inputHash: string } } }) => a.ticket.step.inputHash))
    expect(usage.attempts.every((a: { state: string }) => a.state === "known")).toBe(true)
  } finally { await secondBrowser?.close(); await firstBrowser.close() }
})

test("manual version update during a paused run preserves its captured version and cumulative allowance", async ({ page, request }) => {
  const { writeFile } = await import("node:fs/promises"), { join } = await import("node:path")
  const { skill } = await import("./fixtures/modular")
  await resetTools()
  const { ref, source } = await importTool(request, "Version acceptance")
  const run = await startTool(request, ref, "MODULAR:update", 1)
  await expect.poll(async () => (await snapshot(request, run.id)).status).toBe("paused_limit")
  const prior = await readRunFile(run.id, "usage.json")
  expect(prior.attempts).toHaveLength(1)
  await writeFile(join(source, "SKILL.md"), skill("Version acceptance", "Version two adds a limitation."))
  await page.goto("/tools")
  const card = page.locator("article").filter({ has: page.getByRole("heading", { name: "Version acceptance", exact: true }) })
  await card.getByRole("button", { name: "Manage", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await dialog.getByText("Renew local folder access", { exact: true }).click()
  await dialog.getByLabel("Original package folder").fill(source)
  await dialog.getByLabel("Allow this exact folder for 30 minutes").check()
  await dialog.getByRole("button", { name: "Check for updates", exact: true }).click()
  await expect(dialog.getByRole("button", { name: "Apply reviewed update" })).toBeVisible()
  await dialog.getByRole("button", { name: "Apply reviewed update" }).click()
  await expect(dialog.getByText("Change saved for this profile.")).toBeVisible()
  const library = (await (await request.get("/api/tools?view=library")).json()).result
  const updated = library.tools.find((tool: { name: string }) => tool.name === "Version acceptance")
  expect(updated.ref.digest).not.toBe(ref.digest)
  expect((await readRunFile(run.id, "run.json")).tool).toEqual(ref)
  await page.goto(`/tools/runs/${run.id}`)
  await page.getByRole("button", { name: "Continue", exact: true }).click()
  await expect(page.getByText("Completed", { exact: true })).toBeVisible({ timeout: 25000 })
  const after = await readRunFile(run.id, "usage.json")
  expect(after.attempts).toHaveLength(3)
  expect(after.attempts[0]).toEqual(prior.attempts[0])
  expect(after.extensions).toHaveLength(1)
  expect((await snapshot(request, run.id)).allowance.modelCalls).toBe(31)
  expect((await readRunFile(run.id, "run.json")).tool).toEqual(ref)
  expect((await providerRows("update")).filter(row => row.phase === "review-synthesis")).toHaveLength(1)
})
