import { expect, test } from "@playwright/test"
import { NodeFsVaultStorage } from "../src/lib/vault/node-fs-storage"
import { mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"

test("installed native tools keep core navigation and pinned shortcuts across layouts", async ({ page, request }, info) => {
  const { resetTools } = await import("./fixtures/modular")
  await resetTools()
  await request.post("/api/profile", { data: { name: "Ada", role: "Researcher", fields: "Neuroscience", topics: "Speech", feedPrefs: "Methods" } })
  let runs = 0
  page.on("request", req => { if (req.method() === "POST" && /\/api\/tools\/runs$/.test(req.url())) runs++ })
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto("/tools")
  await page.getByRole("button", { name: "Catalog", exact: true }).click()
  for (const name of ["Trending", "Find papers", "Deep review", "Idea Spark"]) {
    const card = page.locator("article").filter({ has: page.getByRole("heading", { name, exact: true }) })
    await card.getByRole("button", { name: "Add tool", exact: true }).click()
    await expect(card).toHaveCount(0)
  }
  await page.getByRole("button", { name: "Installed", exact: true }).click()
  await expect(page.locator("article")).toHaveCount(4)
  for (const name of ["Trending", "Idea Spark"]) {
    await page.locator("article").filter({ has: page.getByRole("heading", { name, exact: true }) }).getByRole("button", { name: "Pin to sidebar", exact: true }).click()
    await expect(page.getByRole("navigation").getByRole("link", { name, exact: true })).toBeVisible()
  }
  await page.reload()
  const nav = page.getByRole("navigation")
  await expect(nav.getByText("Tools", { exact: true })).toHaveCount(1)
  for (const name of ["Home", "Sparky", "Wiki", "Graph", "Projects", "Tools", "Trending", "Idea Spark", "History"]) {
    await expect(nav.getByRole("link", { name, exact: true })).toBeVisible()
  }
  await expect(page.getByText("Enabled · Ready", { exact: true })).toHaveCount(4)
  await page.screenshot({ path: info.outputPath("tools-installed-readme.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: "Close sidebar", exact: true }).click()
  await expect(page.getByRole("button", { name: "Open sidebar", exact: true })).toBeVisible()
  await expect(nav.getByRole("link", { name: "Tools", exact: true })).toBeInViewport()
  await page.screenshot({ path: info.outputPath("tools-installed-collapsed.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: "Open sidebar", exact: true }).click()
  await page.getByRole("button", { name: /dark mode/i }).click()
  await page.screenshot({ path: info.outputPath("tools-installed-readme-dark.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: /light mode/i }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole("button", { name: "Open menu", exact: true }).click()
  const menu = page.getByRole("dialog", { name: "Navigation menu" })
  await expect(menu.getByText("Tools", { exact: true })).toHaveCount(1)
  await expect(menu.getByRole("link", { name: "Idea Spark", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("tools-installed-mobile-nav.png"), fullPage: true, animations: "disabled" })
  await menu.getByRole("link", { name: "Tools", exact: true }).click()
  await expect(menu).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(runs).toBe(0)
})

test("configured empty default vault has no optional tool scan, provider call or scheduled work", async ({ page, request }, info) => {
  const { readFile } = await import("node:fs/promises")
  const baseline = JSON.parse(await readFile(join(process.env.SCISPARK_E2E_RUN_DIR!, "evidence", "fresh-profile.json"), "utf8"))
  expect(baseline.enabled).toEqual([])
  expect(baseline.runs).toEqual([])
  expect(baseline.providerCalls).toBe(0)
  const storage = new NodeFsVaultStorage(process.env.SCISPARK_E2E_VAULT_PATH!)
  await storage.write(".scispark/tools/state.json", JSON.stringify({ schemaVersion: 1, enabled: [], pins: [], overrides: [], migrated: true, sidebarPins: [] }))
  let scans = 0
  page.on("request", req => { if (req.method() === "POST" && /\/api\/(tools\/discovery|skills\/(trending|spark))/.test(req.url())) scans++ })
  await page.goto("/tools")
  await expect(page.getByRole("heading", { name: "No tools installed" })).toBeVisible()
  await page.screenshot({ path: info.outputPath("empty-profileTools.png"), fullPage: true })
  expect(scans).toBe(0)
  expect((await (await request.get("/api/tools?view=library")).json()).result.tools.filter((tool: { enabled: boolean }) => tool.enabled)).toEqual([])
})

test("Tools empty, installed, explicit local import, consent, setup and errors across desktop and phone", async ({ page, request }, info) => {
  const storage = new NodeFsVaultStorage(process.env.SCISPARK_E2E_VAULT_PATH!)
  await request.post("/api/profile", { data: { name: "Ada", role: "Researcher", fields: "Neuroscience", topics: "Speech", feedPrefs: "Methods" } })
  await storage.write(".scispark/tools/state.json", JSON.stringify({ schemaVersion: 1, enabled: [], pins: [], overrides: [], migrated: true, sidebarPins: [] }))
  const source = join(process.env.SCISPARK_E2E_RUN_DIR!, "explicit-skills")
  await mkdir(source)
  await writeFile(join(source, "SKILL.md"), "---\nname: Research methods helper\ndescription: Compare methods using supplied research context.\nscispark:\n  engines: [api, codex, claude-code]\n---\nCompare supplied sources and preserve limitations.")
  let discoveryCalls = 0, runs = 0
  page.on("request", req => { if (req.method() === "POST" && req.url().includes("/api/tools/discovery")) discoveryCalls++; if (req.method() === "POST" && /\/api\/tools\/runs$/.test(req.url())) runs++ })
  // No execution is required by this library-only check.
  await page.route("**/api/skills/**", route => route.fulfill({ status: 409, json: { error: "Library fixture does not execute models." } }))
  await page.goto("/tools")
  await expect(page.getByRole("heading", { name: "No tools installed" })).toBeVisible()
  await expect(page.getByRole("link", { name: "Trending", exact: true })).toHaveCount(0)
  await expect(page.getByRole("link", { name: "Graph", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("tools-empty-desktop.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: "Catalog", exact: true }).click()
  const trending = page.locator("article").filter({ has: page.getByRole("heading", { name: "Trending", exact: true }) })
  await trending.getByRole("button", { name: "Add tool", exact: true }).click()
  await page.getByRole("button", { name: "Installed", exact: true }).click()
  await trending.getByRole("button", { name: "Pin to sidebar", exact: true }).click()
  await expect(page.getByRole("link", { name: "Trending", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Add tools", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await expect(dialog).toBeFocused(); await page.keyboard.press("Shift+Tab"); expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
  await page.keyboard.press("Escape"); await expect(page.getByRole("button", { name: "Add tools", exact: true })).toBeFocused()
  await page.getByRole("button", { name: "Find installed skills", exact: true }).click()
  await expect(dialog.getByText("Folder path", { exact: true })).toBeVisible()
  expect(discoveryCalls).toBe(0)
  await dialog.getByLabel("Folder path", { exact: true }).fill(source)
  await page.screenshot({ path: info.outputPath("tools-consent-desktop.png"), fullPage: true, animations: "disabled" })
  await dialog.getByLabel(/Allow access/).check(); await dialog.getByRole("button", { name: "Discover skills" }).click()
  await expect(dialog.getByRole("heading", { name: "Research methods helper" })).toBeVisible(); expect(discoveryCalls).toBe(2)
  await dialog.getByRole("button", { name: "Review skill" }).click()
  await dialog.getByLabel(/I reviewed/).check(); await dialog.getByRole("button", { name: "Confirm import" }).click()
  await expect(dialog.getByText(/Import saved/)).toBeVisible()
  await dialog.getByRole("button", { name: "Close", exact: true }).click()
  await expect(page.getByRole("heading", { name: "Research methods helper", exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath("tools-installed-desktop.png"), fullPage: true, animations: "disabled" })
  await page.getByRole("button", { name: "Catalog", exact: true }).click()
  await page.locator("article").filter({ has: page.getByRole("heading", { name: "OpenCite", exact: true }) }).getByRole("button", { name: "Review tool" }).click()
  await dialog.getByRole("button", { name: "Preview OpenCite" }).click()
  await dialog.getByLabel(/I reviewed/).check(); await dialog.getByRole("button", { name: "Confirm import" }).click()
  await expect(dialog.getByText(/Import saved/)).toBeVisible()
  await page.screenshot({ path: info.outputPath("tools-setup-desktop.png"), fullPage: true, animations: "disabled" })
  await dialog.getByRole("button", { name: "Close", exact: true }).click()
  await page.getByRole("button", { name: "Installed", exact: true }).click()
  await expect(page.getByRole("button", { name: "Installed", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath("tools-installed-phone.png"), fullPage: true, animations: "disabled" })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const openCite = page.locator("article").filter({ has: page.getByRole("heading", { name: "OpenCite", exact: true }) })
  await openCite.getByRole("button", { name: "Manage" }).click()
  await expect(dialog.getByText(/Changes apply to new runs/)).toBeVisible()
  await page.screenshot({ path: info.outputPath("tools-settings-phone.png"), fullPage: true, animations: "disabled" })
  await page.keyboard.press("Escape")
  await page.getByRole("button", { name: "Add tools", exact: true }).click(); await dialog.getByRole("button", { name: "Local files or folder" }).click()
  await dialog.getByLabel("Folder path", { exact: true }).fill(join(source, "missing")); await dialog.getByRole("button", { name: "Preview selected folder" }).click()
  await expect(dialog.getByRole("alert")).toBeVisible()
  await page.screenshot({ path: info.outputPath("tools-error-phone.png"), fullPage: true, animations: "disabled" })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press("Escape")
  await expect(dialog).toBeHidden()
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.getByRole("button", { name: /dark mode/i }).click()
  await page.screenshot({ path: info.outputPath("tools-installed-dark.png"), fullPage: true, animations: "disabled" })
  expect(runs).toBe(0)
})

test("import hands an unbound supporting connection to root Manage without claiming readiness", async ({ page, request }, info) => {
  const storage = new NodeFsVaultStorage(process.env.SCISPARK_E2E_VAULT_PATH!)
  const source = join(process.env.SCISPARK_E2E_RUN_DIR!, "supporting-connection")
  const rootSource = join(process.env.SCISPARK_E2E_RUN_DIR!, "supporting-root")
  await Promise.all([mkdir(source), mkdir(rootSource)])
  await writeFile(join(source, "SKILL.md"), `---\nname: Literature connection helper\ndescription: Search scholarly sources.\nscispark: ${JSON.stringify({ engines: ["api"], connections: ["semantic-scholar"], setup: { commands: [], runtimes: [], unsupported: [], connectionAdapter: "scispark-http-v1" } })}\n---\nUse the declared source connection.`)
  const previewResponse = await request.post("/api/tools/imports", { data: { source: { kind: "local-folder", path: source } } })
  expect(previewResponse.ok()).toBe(true)
  const preview = (await previewResponse.json()).result
  const confirmed = await request.post(`/api/tools/imports/${preview.id}`, { data: { action: "confirm", selected: [preview.tools[0].manifest.ref], proposals: [preview.tools[0].proposal] } })
  expect(confirmed.ok()).toBe(true)
  const helper = (await confirmed.json()).result.preview.tools[0].manifest.ref
  // Fixture topology: retain the owned immutable helper, but no standalone binding.
  await storage.write(".scispark/tools/state.json", JSON.stringify({ schemaVersion: 1, enabled: [], pins: [], overrides: [], migrated: true, sidebarPins: [] }))
  const settings = JSON.parse((await storage.read(".scispark/settings.json"))!)
  await storage.write(".scispark/settings.json", JSON.stringify({ ...settings, paperSources: { s2: { apiKey: "disposable-fixture-only" } } }))
  await writeFile(join(rootSource, "SKILL.md"), `---\nname: Literature research root\ndescription: Compare supplied evidence.\nscispark: ${JSON.stringify({ engines: ["api"], dependencies: [helper] })}\n---\nUse the declared supporting skill.`)
  let runs = 0
  page.on("request", req => { if (req.method() === "POST" && /\/api\/tools\/runs$/.test(req.url())) runs++ })
  await page.goto("/tools")
  await page.getByRole("button", { name: "Add tools", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await dialog.getByRole("button", { name: "Local files or folder" }).click()
  await dialog.getByLabel("Folder path", { exact: true }).fill(rootSource)
  await dialog.getByRole("button", { name: "Preview selected folder" }).click()
  await dialog.getByLabel(/I reviewed/).check()
  await dialog.getByRole("button", { name: "Confirm import" }).click()
  await expect(dialog.getByText("Import saved.", { exact: true })).toBeVisible()
  await expect(dialog.getByText(/Needs setup:/)).toBeVisible()
  await expect(dialog.getByText("Supporting tool needing setup", { exact: true })).toBeVisible()
  await expect(dialog.locator("p").filter({ hasText: "Supporting tool needing setup" }).getByText("Literature connection helper", { exact: true })).toBeVisible()
  await expect(dialog.getByText(/^Ready:/)).toHaveCount(0)
  await page.screenshot({ path: info.outputPath("supporting-import-desktop.png"), fullPage: true, animations: "disabled" })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath("supporting-import-phone.png"), fullPage: true, animations: "disabled" })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await dialog.getByRole("button", { name: "Manage setup" }).click()
  await expect(dialog).toHaveAttribute("aria-label", "Literature research root")
  await expect(dialog).toBeFocused()
  await page.keyboard.press("Shift+Tab")
  expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBe(true)
  const connect = dialog.getByRole("button", { name: "Connect Semantic Scholar for Literature connection helper" })
  await expect(connect).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath("supporting-manage-phone.png"), fullPage: true, animations: "disabled" })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await connect.click()
  await expect(dialog.getByText("Change saved for this profile.")).toBeVisible()
  await expect(dialog.getByText("Supporting tool connection", { exact: true })).toHaveCount(1)
  await page.keyboard.press("Escape")
  const card = page.locator("article").filter({ has: page.getByRole("heading", { name: "Literature research root", exact: true }) })
  await expect(card.getByText("Enabled · Ready", { exact: true })).toBeVisible()
  await card.getByRole("button", { name: "Manage" }).click()
  await page.keyboard.press("Escape")
  await expect(card.getByRole("button", { name: "Manage" })).toBeFocused()
  await expect(page.getByRole("heading", { name: "Literature connection helper", exact: true })).toHaveCount(0)
  expect(runs).toBe(0)
})


test("GitHub and ZIP fixture imports use the reviewed UI and network misses fail closed", async ({ page, request }) => {
  const { zipSync, strToU8 } = await import("fflate")
  const { skill, resetTools } = await import("./fixtures/modular")
  await resetTools()
  const root = process.env.SCISPARK_E2E_RUN_DIR!
  await writeFile(join(root, "github-fixture.zip"), zipSync({ "fixture-root/SKILL.md": strToU8(skill("GitHub fixture evidence")) }))
  await page.goto("/tools")
  await page.getByRole("button", { name: "Add tools", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await dialog.getByRole("button", { name: "GitHub", exact: true }).click()
  await dialog.getByLabel("GitHub repository").fill("https://github.com/scispark-fixture/modular")
  await dialog.getByRole("button", { name: "Preview import", exact: true }).click()
  await expect(dialog.getByRole("checkbox", { name: "GitHub fixture evidence", exact: true })).toBeVisible()
  await dialog.getByLabel(/I reviewed/).check(); await dialog.getByRole("button", { name: "Confirm import" }).click()
  await expect(dialog.getByText("Import saved.", { exact: true })).toBeVisible()
  await dialog.getByRole("button", { name: "Close", exact: true }).click()
  await page.getByRole("button", { name: "Add tools", exact: true }).click()
  await dialog.getByRole("button", { name: "Local files or folder" }).click()
  await dialog.getByLabel("Or upload a ZIP file").setInputFiles({ name: "fixture.zip", mimeType: "application/zip", buffer: Buffer.from(zipSync({ "SKILL.md": strToU8(skill("ZIP fixture evidence")) })) })
  await expect(dialog.getByRole("checkbox", { name: "ZIP fixture evidence", exact: true })).toBeVisible()
  await dialog.getByLabel(/I reviewed/).check(); await dialog.getByRole("button", { name: "Confirm import" }).click()
  await expect(dialog.getByText("Import saved.", { exact: true })).toBeVisible()
  const missing = await request.post("/api/tools/imports", { data: { source: { kind: "github", url: "https://github.com/scispark-fixture/unmatched" } } })
  expect(missing.status()).toBe(409)
})
