import { z } from "zod"

/** Evidence coverage is recorded by the runtime, never generated by the model. */
export const PaperTextInfoSchema = z.object({
  access: z.enum(["full-text", "abstract"]),
  locator: z.string(),
  checkedAt: z.string().datetime(),
  truncated: z.boolean(),
  notes: z.array(z.string()),
})
export const PaperTextSchema = PaperTextInfoSchema.extend({
  paperKey: z.string(),
  text: z.string().max(45_000),
})
export type PaperTextInfo = z.infer<typeof PaperTextInfoSchema>
export type PaperText = z.infer<typeof PaperTextSchema>
